Fix JsonNumber bson serialization
micronaut-projects/micronaut-serialization pull request #898
Opened 2024-07-23 16:59 UTC by rorueda

- Always use the right number type when serializing, so formats that support the type info can deserialize to the correct type. Currently, if you serialize an `int JsonNumber`, when deserializing you get a `long JsonNumber`.
- Fix fallback deserialization of custom `Number` implementations. The bson decoder advances when `getBigDecimal` is called - so, in the second call you either get an exception or one of the fields is swallowed.
- Fix element index increment when serializing `BigInteger`. Increment is already done by `encodeBigDecimal`.

2024-07-23 16:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-serialization?pullRequest=898) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-serialization?pullRequest=898) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-serialization?pullRequest=898) it.</sub>

2024-07-24 07:21 UTC, dstepanov requested changes

2024-07-24 07:21 UTC, dstepanov commented on serde-bson/src/main/java/io/micronaut/serde/bson/BsonReaderDecoder.java
> +        return ((Decimal128) number).bigDecimalValue();
This can be implemented using instanceOf or different convertions

2024-07-24 07:34 UTC, yawkat commented on serde-support/src/main/java/io/micronaut/serde/support/AbstractStreamDecoder.java
> +        throw new UnsupportedOperationException();
Definitely needs a proper default implementation.

2024-10-29 08:13 UTC, merged

2024-10-29 08:13 UTC, dstepanov commented
Thanks for the PR. I have corrected the new method.